services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - SITE_URL=${SITE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_NAME=${DB_NAME}
      - REDIS_ADDR=redis:6379
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    volumes:
      - .:/app
    tty: true # For "npm run watch:css" https://github.com/rails/rails/issues/44048
    depends_on:
      - postgres
      - redis
    # command: ["sh", "/app/scripts/start.sh"]
    # command: ["/bin/sh", "-c", "cd /app/web && npm run watch:css"]

  postgres:
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #     GUNICORN_ACCESS_LOGFILE: "/dev/null"
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - pgadmindata:/var/lib/pgadmin
  #   depends_on:
  #     - postgres

  redis:
    image: redis:7.4.1-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  # pgadmindata:
