FROM golang:1.23.3-alpine3.20

RUN apk update && apk add --no-cache bash nodejs npm mc
WORKDIR /app

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN addgroup -g ${GROUP_ID} appgroup && \
    adduser -u ${USER_ID} -G appgroup -s /bin/sh -D appuser && \
    chown -R appuser:appgroup /app
USER appuser

COPY go.mod go.sum ./
RUN go mod download && go mod verify

RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/pressly/goose/v3/cmd/goose@latest

EXPOSE 8080

CMD ["/bin/sh", "-c", "./scripts/migrate.sh up && ./server"]