services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - TIME_TRACKER_ENV=development
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/web/node_modules # чтобы не перезаписывать node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
